$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1457448328735.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cb7cd3fc1fe3492d9de5b7d5f69968fa",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFF000000},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b121cd299ab24a318ce5c577785fbc3f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":333,
              "height":643}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a824e96ea2cf4e119563e2c786413269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":333,
                  "height":643}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"6c4bf5c9440a4f04a62bc886a733bf59",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":53},
            "size":{
              "width":301,
              "height":537}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6c042a56b7b34cb7982d0b4f764aa7e2",
              "label":"待机页面",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cef610f7996d4e0584814ecf307d4a05",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":301,
                      "height":535}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e8973e2dd2e4481fa80cf27a86130d76",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":301,
                          "height":535}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u3.png"}}]},
{
              "id":"836c5228e1e3495c8afc45928a3be37a",
              "label":"欢迎页面",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"75d8f302bd044552982b75574174b713",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f11e10717aaf46f79a321c28746875d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Panel to State",
                              "panelsToStates":[]},
{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 引导页 向左滑动 out 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":6,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u5.png"}}]},
{
              "id":"ddab75d72785488da800f06d27b89162",
              "label":"首页",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c3264e8786e94870af10bb2adf83a145",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b275074173304f7aa7be52d93e15ad00",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 首页2 向上滑动 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":4,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"slideUp",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u7.jpg"}},
{
                  "id":"6074991fed5045b98bfedc2ec237a9d7",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":225,
                      "y":24},
                    "size":{
                      "width":65,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Panel to State",
                              "panelsToStates":[]},
{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 注册页 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":11,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"f487dd185c034484a0d3e26b16e2f2cd",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":495},
                    "size":{
                      "width":50,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 私人定制 淡入淡出 out 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":13,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"69962e5dc26e40b1aaf344984f0c01b1",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":239,
                      "y":495},
                    "size":{
                      "width":41,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 个人空间",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":15,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"7fd57d97206346d181c44bf421c96ce5",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":170,
                      "y":495},
                    "size":{
                      "width":50,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 美丽学院 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":18,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"86457e81461a4f7da0f552c261ae2e9d",
              "label":"首页2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e6d3d87b60334efaa269dbf86e893873",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0e31a60b436040ef9e70f23e53facbdd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 首页3 向上滑动 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":5,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"slideUp",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u13.jpg"}}]},
{
              "id":"a4ff2393cd264787a32709eb37fa013f",
              "label":"首页3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"44b1f04ab6c646ae803c6609eea5934f",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b0d82bf4f5414e7583b19471bf5140ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u15.jpg"}},
{
                  "id":"34dc4de2e2614238afc37da93230ffb6",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":27},
                    "size":{
                      "width":50,
                      "height":23}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 首页 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"dc4cd78eceef4122b84dcb6cb144aed0",
              "label":"引导页",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"995a7880172d43f2a25188dc490f465c",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-20,
                      "y":0},
                    "size":{
                      "width":320,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"52ed72ef19c24522add88c553bc670fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-20,
                          "y":0},
                        "size":{
                          "width":320,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Panel to State",
                              "panelsToStates":[]},
{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 引导页2 向左滑动 out 500ms 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":7,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u18.jpg"}}]},
{
              "id":"caa6f9b2d41649f6966b6cd14fa62956",
              "label":"引导页2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7d89ae31edc24105b2c125e772ec9ae4",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-11,
                      "y":0},
                    "size":{
                      "width":311,
                      "height":536}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f2aaf2f0335a491f8ca420aea1c86ebd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-11,
                          "y":0},
                        "size":{
                          "width":311,
                          "height":536}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Panel to State",
                              "panelsToStates":[]},
{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 引导页3 向左滑动 out 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":8,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u20.jpg"}}]},
{
              "id":"4a6dbcf26ab24b85a31e2faf629f98a0",
              "label":"引导页3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a8c4cb7f56bb42138ebeee8b51dfcfc9",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-21},
                    "size":{
                      "width":300,
                      "height":558}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"225469b8ad1245418a1e9e4e02068ab2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-21},
                        "size":{
                          "width":300,
                          "height":558}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Panel to State",
                              "panelsToStates":[]},
{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 引导页4 向左滑动 out 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":9,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u22.jpg"}}]},
{
              "id":"ff358828c8e5473eb110b778c53ac6c0",
              "label":"引导页4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"77c8a2b5bf904631ae38d533ba56c1b0",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"37569a1a5a7a4e18aeb88753535586d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 首页 淡入淡出 out 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u24.png"}}]},
{
              "id":"e563412c5fb64c81867f3c050253ff0f",
              "label":"登录页",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1c79aa5d51f346769f56ac005c975cd3",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":302,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"415973007d894446a03278fe34a8dc78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":302,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u26.jpg"}},
{
                  "id":"2be18b07e4644183900e6879826b22c6",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":126,
                      "y":390},
                    "size":{
                      "width":50,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Panel to State",
                              "panelsToStates":[]},
{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 首页 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"4431dd847bd84acc95ea1792a36760d4",
              "label":"注册页",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d3a4d6452bbe4d21a1e8bd3532028a42",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e243a65ee199481cbebba2f6a29ea565",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u29.jpg"}},
{
                  "id":"840ef9e079b842c798aafad22f302326",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":240,
                      "y":26},
                    "size":{
                      "width":50,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Panel to State",
                              "panelsToStates":[]},
{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 登录页 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":10,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"0efbef7e5dba45f2b286de152fbdb76a",
              "label":"搜索页",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"951ab07f9251497d80294cec94d5e9b1",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c0caf4be8bf14a8c90801f4614628f9b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u32.jpg"}},
{
                  "id":"330422cd50fa467f9a8e5fabad92a13a",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":24},
                    "size":{
                      "width":50,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 首页 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"e045a62f94d640f190cb4e1a82da223e",
              "label":"私人定制",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5769d1db4b344fdfbfdf061e05cbe338",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"20340e96caaa41bc8791e1ac5bd10483",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u35.jpg"}},
{
                  "id":"863d7d33cf56489e8e55be456e8d59db",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":85},
                    "size":{
                      "width":270,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 搜索页 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":12,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"65b2491319df477e8ed1e4eb9791af96",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":179,
                      "y":160},
                    "size":{
                      "width":91,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 私人定制2 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":14,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}}}]},
{
              "id":"64d6506ed1c54232a0e28a92710bae69",
              "label":"私人定制2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e1a669b18c9e4f07b98e2cdf53b796ab",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0ee111507a946249a85695e19d21523",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u39.jpg"}},
{
                  "id":"7547100fde1b4468bca38f84cc77e1f3",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":20},
                    "size":{
                      "width":50,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 私人定制",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":13,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"21ec6b03d10d4701bcb9340f5317d862",
              "label":"个人空间",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6f2cbe1ca02f47b9977fa27ed74b2def",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-10},
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ec67a058efa4a319a63cc3beef1b244",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-10},
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u42.png"}},
{
                  "id":"136547b8426f41b9847eea78072d291c",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":96,
                      "y":281},
                    "size":{
                      "width":121,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 个人空间3 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":16,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"5e128127ae9f4d7c98a6e731e141403f",
              "label":"个人空间3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"dae05e3b20a14be59ce1150a31baf928",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e14a6cccde54d0fab0bb1b8a4a01f4d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u45.jpg"}},
{
                  "id":"6dd815acb9ba492fa94273f2d53e41d7",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":26},
                    "size":{
                      "width":50,
                      "height":24}},
                  "adaptiveStyles":{
}},
{
                  "id":"c2146dfdedc74d1195d935f0390a5237",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":25,
                      "y":125},
                    "size":{
                      "width":265,
                      "height":165}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 收藏页面 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":17,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"2e159c07bc204012980b9923d08681f7",
              "label":"收藏页面",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"02149b179e234a21ac2f3d00aef9e523",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":302,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c9de80f4f2346789522c310f7e126dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":302,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u49.jpg"}},
{
                  "id":"4eb25558c3314b4ea586eee59176373a",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14.7999992370605,
                      "y":20},
                    "size":{
                      "width":50,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 首页 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"9101f336707149269c1d0cd4472b569c",
              "label":"美丽学院",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"10f5308acc624b5bba21794a3e6ec287",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c62e0bf5700d4cf28648dd277ffafbd8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u52.jpg"}},
{
                  "id":"8a5b3aa508a042cc8f5e2c10dce07ef2",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":86},
                    "size":{
                      "width":70,
                      "height":74}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 美丽学院2",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":19,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"85e5fb844d3a4e2986a5a250e61fbf0a",
              "label":"美丽学院2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6020db44cb9541eeab631b01c4fecddd",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7cb5e85102914de6a93c4e988946f5e9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u55.jpg"}},
{
                  "id":"1bca1848ccc5409ebe606281bbb4983c",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":80},
                    "size":{
                      "width":255,
                      "height":23}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setWidgetSize",
                              "description":"Set Size of Panel",
                              "objectsToResize":[]},
{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 搜索页 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":12,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"96710e23258e4970ac370d44aa7b6808",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":140},
                    "size":{
                      "width":110,
                      "height":110}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 教学视频 淡入淡出 out 500ms 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":20,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"33b0a5c9a4df41489bfbd2513eb326ae",
              "label":"教学视频",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4e8473cd2c964aafac3c36dc18f620ce",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":537}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12a3f4904fab4122b58deabe050bd9f4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":537}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u59.jpg"}},
{
                  "id":"86b7e5115dcb4dea93a9835b073d15d5",
                  "label":"",
                  "parentDynamicPanel":"6c4bf5c9440a4f04a62bc886a733bf59",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":310},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 首页",
                              "panelsToStates":[{
                                  "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"06dd13e289294ea8b1bf3a9373859f04",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":330},
            "size":{
              "width":50,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]},
{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) to 欢迎页面 淡入淡出 out 500ms",
                      "panelsToStates":[{
                          "panelPath":["6c4bf5c9440a4f04a62bc886a733bf59"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "b121cd299ab24a318ce5c577785fbc3f":{
      "scriptId":"u0"},
    "a824e96ea2cf4e119563e2c786413269":{
      "scriptId":"u1"},
    "6c4bf5c9440a4f04a62bc886a733bf59":{
      "scriptId":"u2"},
    "cef610f7996d4e0584814ecf307d4a05":{
      "scriptId":"u3"},
    "e8973e2dd2e4481fa80cf27a86130d76":{
      "scriptId":"u4"},
    "75d8f302bd044552982b75574174b713":{
      "scriptId":"u5"},
    "f11e10717aaf46f79a321c28746875d9":{
      "scriptId":"u6"},
    "c3264e8786e94870af10bb2adf83a145":{
      "scriptId":"u7"},
    "b275074173304f7aa7be52d93e15ad00":{
      "scriptId":"u8"},
    "6074991fed5045b98bfedc2ec237a9d7":{
      "scriptId":"u9"},
    "f487dd185c034484a0d3e26b16e2f2cd":{
      "scriptId":"u10"},
    "69962e5dc26e40b1aaf344984f0c01b1":{
      "scriptId":"u11"},
    "7fd57d97206346d181c44bf421c96ce5":{
      "scriptId":"u12"},
    "e6d3d87b60334efaa269dbf86e893873":{
      "scriptId":"u13"},
    "0e31a60b436040ef9e70f23e53facbdd":{
      "scriptId":"u14"},
    "44b1f04ab6c646ae803c6609eea5934f":{
      "scriptId":"u15"},
    "b0d82bf4f5414e7583b19471bf5140ec":{
      "scriptId":"u16"},
    "34dc4de2e2614238afc37da93230ffb6":{
      "scriptId":"u17"},
    "995a7880172d43f2a25188dc490f465c":{
      "scriptId":"u18"},
    "52ed72ef19c24522add88c553bc670fe":{
      "scriptId":"u19"},
    "7d89ae31edc24105b2c125e772ec9ae4":{
      "scriptId":"u20"},
    "f2aaf2f0335a491f8ca420aea1c86ebd":{
      "scriptId":"u21"},
    "a8c4cb7f56bb42138ebeee8b51dfcfc9":{
      "scriptId":"u22"},
    "225469b8ad1245418a1e9e4e02068ab2":{
      "scriptId":"u23"},
    "77c8a2b5bf904631ae38d533ba56c1b0":{
      "scriptId":"u24"},
    "37569a1a5a7a4e18aeb88753535586d1":{
      "scriptId":"u25"},
    "1c79aa5d51f346769f56ac005c975cd3":{
      "scriptId":"u26"},
    "415973007d894446a03278fe34a8dc78":{
      "scriptId":"u27"},
    "2be18b07e4644183900e6879826b22c6":{
      "scriptId":"u28"},
    "d3a4d6452bbe4d21a1e8bd3532028a42":{
      "scriptId":"u29"},
    "e243a65ee199481cbebba2f6a29ea565":{
      "scriptId":"u30"},
    "840ef9e079b842c798aafad22f302326":{
      "scriptId":"u31"},
    "951ab07f9251497d80294cec94d5e9b1":{
      "scriptId":"u32"},
    "c0caf4be8bf14a8c90801f4614628f9b":{
      "scriptId":"u33"},
    "330422cd50fa467f9a8e5fabad92a13a":{
      "scriptId":"u34"},
    "5769d1db4b344fdfbfdf061e05cbe338":{
      "scriptId":"u35"},
    "20340e96caaa41bc8791e1ac5bd10483":{
      "scriptId":"u36"},
    "863d7d33cf56489e8e55be456e8d59db":{
      "scriptId":"u37"},
    "65b2491319df477e8ed1e4eb9791af96":{
      "scriptId":"u38"},
    "e1a669b18c9e4f07b98e2cdf53b796ab":{
      "scriptId":"u39"},
    "d0ee111507a946249a85695e19d21523":{
      "scriptId":"u40"},
    "7547100fde1b4468bca38f84cc77e1f3":{
      "scriptId":"u41"},
    "6f2cbe1ca02f47b9977fa27ed74b2def":{
      "scriptId":"u42"},
    "7ec67a058efa4a319a63cc3beef1b244":{
      "scriptId":"u43"},
    "136547b8426f41b9847eea78072d291c":{
      "scriptId":"u44"},
    "dae05e3b20a14be59ce1150a31baf928":{
      "scriptId":"u45"},
    "7e14a6cccde54d0fab0bb1b8a4a01f4d":{
      "scriptId":"u46"},
    "6dd815acb9ba492fa94273f2d53e41d7":{
      "scriptId":"u47"},
    "c2146dfdedc74d1195d935f0390a5237":{
      "scriptId":"u48"},
    "02149b179e234a21ac2f3d00aef9e523":{
      "scriptId":"u49"},
    "2c9de80f4f2346789522c310f7e126dd":{
      "scriptId":"u50"},
    "4eb25558c3314b4ea586eee59176373a":{
      "scriptId":"u51"},
    "10f5308acc624b5bba21794a3e6ec287":{
      "scriptId":"u52"},
    "c62e0bf5700d4cf28648dd277ffafbd8":{
      "scriptId":"u53"},
    "8a5b3aa508a042cc8f5e2c10dce07ef2":{
      "scriptId":"u54"},
    "6020db44cb9541eeab631b01c4fecddd":{
      "scriptId":"u55"},
    "7cb5e85102914de6a93c4e988946f5e9":{
      "scriptId":"u56"},
    "1bca1848ccc5409ebe606281bbb4983c":{
      "scriptId":"u57"},
    "96710e23258e4970ac370d44aa7b6808":{
      "scriptId":"u58"},
    "4e8473cd2c964aafac3c36dc18f620ce":{
      "scriptId":"u59"},
    "12a3f4904fab4122b58deabe050bd9f4":{
      "scriptId":"u60"},
    "86b7e5115dcb4dea93a9835b073d15d5":{
      "scriptId":"u61"},
    "06dd13e289294ea8b1bf3a9373859f04":{
      "scriptId":"u62"}}});